name: generate-binary-matrix

# Example workflow_call:
#
# generate-binary-matrix:
#   uses: ./.github/workflows/_generate-binary-matrix.yml
#   with:
#     package-type: wheel
#     os: linux
#     accelerator-type: cpu

on:
  workflow_call:
    inputs:
      package-type:
        required: true
        type: string
        description: Type of binary package to build (wheel libtorch)
      os:
        required: true
        type: string
        description: Operating system to build for
      accelerator-type:
        required: true
        type: string
        description: Accelerator type to build for
    outputs:
      matrix:
        description: The generated matrix
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Generate matrix
        id: set-matrix
        run: |
          # Set default values
          PACKAGE_TYPE="${{ inputs.package-type }}"
          OS="${{ inputs.os }}"
          ACCELERATOR_TYPE="${{ inputs.accelerator-type }}"

          set +x

          python3 .cd/generate_build_matrix.py \
            --package-type "${PACKAGE_TYPE}" \
            --os "${OS}" \
            --accelerator-type "${ACCELERATOR_TYPE}" \
            --to-github-output
